name: Deploy Blnk to Azure

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: 'ubuntu-latest'
  
      steps:
      - uses: actions/checkout@v2
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://blnkacr.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_dac0f0d637b24cceb83cabd056fed575 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_2845d847730c45c9b69371477d9c7ad1 }}
  
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: blnkacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dac0f0d637b24cceb83cabd056fed575 }}/blnk:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
  
      steps:
      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: blnkacr
          containerAppName: blnk-server
          resourceGroup: rg-blnk-core-dev
          imageToDeploy: 'blnkacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dac0f0d637b24cceb83cabd056fed575 }}/blnk:${{ github.sha }}'
